CREATE TABLE UFOODS
(	UNAME VARCHAR(64),
	FOFFSET INT,
	FGROUP VARCHAR(64),
	FNAME VARCHAR(128),
	FNDBNO VARCHAR(32),
    FDS VARCHAR(32),
    FWEIGHT FLOAT,
    FMEASURE VARCHAR(64),
	FCALORY FLOAT,
	AMOUNT INT,
    PRIMARY KEY (FNAME, FGROUP)
);