CREATE TABLE UFOOD
(	UNAME VARCHAR(64),
	FOFFSET INT,
	FGROUP VARCHAR(64),
	FNAME VARCHAR(64),
	FNDBNO VARCHAR(32),
    FDS VARCHAR(32),
    FCALORY BIGINT,
    FINGRED VARCHAR(256),
    PRIMARY KEY (FNAME)
);