CREATE TABLE USERS
(	UNAME VARCHAR(64),
    PASS VARCHAR(256), 
    NAME VARCHAR(32),
    SURNAME VARCHAR(32),
    AGE VARCHAR(3),
    GENDER VARCHAR(1),
    COMMENT VARCHAR(1024),
    HEIGHT FLOAT,
    WEIGHT FLOAT,
    BMI FLOAT,
    PRIMARY KEY (UNAME)
);